Mages:
- Florent5929
- arimav
- Kuanila
- Mantriton
- Aethrys28
- Inposa
- Leiilaa
- BleedMC
  
Ogres:
- Seris_
- beautifulreal
# Pour cette version 1 du plugin, il n'est pas possible d'ajouter ou de supprimer des mots, qui doivent rester à 186. 
# TOUTEFOIS, il est possible de les modifier.
MotsOgre :
- Splach 
- Sprotch 
- Frakass 
- Bragoul 
- Hounk 
- Glikido 
- Aglou 
- Louk 
- Gola 
- Zyva 
- Tako 
- Gnagola 
- Kopain 
- Jolzio 
- Opog 
- Splonrch 
- Goulada 
- Gasna 
- Plaktu 
- Algo 
- Broum 
- Drulugah 
- Zoulag 
- Goulak 
- Dlakou 
- Zoubla 
- Atoonza 
- Zatal 
- Zamok 
- Dzoubala 
- Taak 
- Rbindeboi 
- Gnagolo 
- Agol 
- Splati 
- Zpotla 
- Gluku 
- Glouglou 
- Slouba 
- Gotfeurdom 
- Dlabou 
- Boulik 
- Bourrino 
- Talok 
- Popoh 
- Vo 
- Zulu 
- Grao 
- Znivo 
- Gof 
- Tounda 
- Vrotapa 
- Oklagh 
- Veuk 
- Volo 
- Dzo 
- Hopla 
- Gorki 
- Doulo 
- Tol 
- Toudlag 
- Grunt 
- Tlakoh
- Zog 
- Akiita
- Houla 
- Schlobok 
- Toko 
- Eto 
- Aknouh 
- Dodo 
- Dragoulou 
- Doumva 
- Gnolo 
- Galoun 
- Kalounga 
- Inta 
- Ol 
- Shlova 
- Gloudouk 
- Ixpe 
- Koulaga
- Djinlgebelh 
- Zoul 
- Hatlouk 
- Glorkou 
- Zogdo 
- Zavol 
- Mourk 
- Glagla 
- Razogh 
- Grok 
- Sakoul 
- Gobbo 
- Palaf 
- Grouf 
- Tagala 
- Gol 
- Droula 
- Gratgrat 
- Ma 
- Faloukou 
- Ugluduk 
- Toulos 
- Yabo 
- Cuicui 
- Yagourt 
- Broudaf 
- Glakoul 
- Chokma
- Taka 
- Hol 
- Miam miam 
- Bozoh 
- Amzo 
- Doula 
- Zaloss 
- Achilika 
- Talof
- Zom 
- Dorva 
- Nanana 
- Bah 
- Atoulka 
- Blok 
- Dkajo 
- Zoub 
- Tablok 
- Kagoula 
- Orkoum 
- Glakou 
- Zogla 
- Zog zog
- Golo 
- Dak 
- Zomva 
- Azerofh 
- Tchok
- Noal 
- Tagoula 
- Da 
- Zod 
- Dar 
- Doordo 
- Borka 
- Gruh 
- Zadoum 
- Makkd'oh 
- Forlaa 
- Kadoula 
- Gravoz 
- Agh
- Zof 
- Crao 
- Beula 
- Zaboufka 
- Swobok 
- Huk
- Azodo 
- Goz 
- Clog 
- Bok 
- Pouk 
- Turlu 
- Exta 
- Glok 
- Ati 
- Rova 
- Tadla 
- Etso 
- Gloubok 
- Groubouf 
- Toka 
- plaf 
- Toukala 
- Toukalo 
- Kligudu 
- Dam 
- Dalouk 
- Kal kal
- Gnagof 
- Cuicui
- Akala
- Bladola 
- plaf
