# Plus de détails ici : https://docs.google.com/document/d/1A9VU9sJ_cVQNxAMNzUynPVhk3ftXGdmVqwWyTrvajQA/edit?usp=sharing
name: fr_Florent59_LangageOgre
main: fr.Florent59.LangageOgre.main
version: 1.12.2
description: Plugin cree pour le serveur Naheulcraft. Il permet aux ogres de n'etre compris que par les autres ogres, les mages ou les operateurs.
author: Florent59
commands:
 addogre:
  description: Ajoute un ogre dans la config
  permission: op
 delogre:
  description: Supprime un ogre dans la config
  permission: op
 showogres:
  description: Montre tous les ogres de la config
  permission: op
 addmage:
  description: Ajoute un mage dans la config
  permission: op
 delmage:
  description: Supprime un mage dans la config
  permission: op
 showmages:
  description: Montre tous les mages de la config
  permission: op
  